### ISSUE TITLE
I'm looking for a static version of awk for armv7

### ISSUE THREAD

**Issue by garilla22** [spakin/awk#10]
Help me find!!

**Comment by spakin** [comment]
The [`awk` package for Go](https://github.com/spakin/awk) is native Go and should therefore have no dynamic dependencies.  Are you perhaps referring to a standalone `awk` binary for armv7?  If so, then this is the wrong place to ask.  That said, perhaps you can compile `awk` yourself from source, using `-static` on the compile/link lines to produce a static binary.

— Scott

**Comment by garilla22** [comment]
Well, okay, I'll translate all the programs on Android under armv7 then post it all on the githab and become famous until the losers
