### ISSUE TITLE
Any way to clear a field

### ISSUE THREAD

**Issue by suntong** [spakin/awk#13]
Hi, 

How to clear a field, like `awk`'s `$1=""` operation (after which the first field is cleared)?

```
$ seq 12 | xargs -n 3 | tee /dev/tty | awk '{ $1=""}; 1;'
1 2 3
 2 3
4 5 6
 5 6
7 8 9
 8 9
10 11 12
 11 12
```

I was trying with `s.SetF(1, "")`, but got the error of:

    cannot use "" (type string) as type *awk.Value in argument to s.SetF

**Comment by spakin** [comment]
The error message seems clear to me.  Try
```Go
s.SetF(1, s.NewValue(""))
```

**Comment by suntong** [comment]
Oops, yes, sorry. thx.
