### ISSUE TITLE
awk.Begin

### ISSUE THREAD

**Issue by FrankReh** [spakin/awk#2]
Example shows awk.Begin being used as global pattern function but this doesn't compile.  Current version of awk package doesn't define it.  Example code sets s.Begin directly.  Probably just the example code needs updating.

**Comment by spakin** [comment]
You're absolutely right.  Commit 69e06a4994a6dc21de78b1c583838dea834abf6f updates the [`awk` package's `README.md` file](https://github.com/spakin/awk/blob/69e06a4994a6dc21de78b1c583838dea834abf6f/README.md) to show instead an assignment to the `Script`'s `Begin` field.

Thanks for the bug report.
