### ISSUE TITLE
How to use GetLine to skip line

### ISSUE THREAD

**Issue by suntong** [spakin/awk#5]
Hi, 

Please take a look at my trial code of using GetLine to skip line:

https://github.com/suntong/lang/blob/master/lang/Go/src/text/awk/SkipLine.go

I run it like this:

    seq 12 | xargs -n 3 | go run SkipLine.go

I.e., the input to the script will look like this:

```
$ seq 12 | xargs -n 3
1 2 3
4 5 6
7 8 9
10 11 12
```

I want (and coded) the script to validate the first line, then skip the following lines until a line begins with "7". However, it is not behaving as I expected. the loop runs forever. 

How can I fix it? 

Thanks

**Comment by suntong** [comment]
Confirmed that it is a bug -- according to https://godoc.org/github.com/spakin/awk#Script.GetLine

> If the argument to GetLine is nil, GetLine reads from the current input stream and increments NR. 

However, I found that the NR never increased, and GetLine kept returning the next line without advancing. The is not the behavior of `awk getline`.

**Comment by suntong** [comment]
Adding Next() into the `Getline` loop does not advance the NR either. Please see the updated [SkipLine.go](https://github.com/suntong/lang/blob/master/lang/Go/src/text/awk/SkipLine.go) for proof.

**Comment by spakin** [comment]
I'm not sure exactly what your script is supposed to do, but I suspect that the problem is with `Next` rather than with `GetLine`.  Could you please post an AWK version of [`SkipLine.go`](https://github.com/suntong/lang/blob/master/lang/Go/src/text/awk/SkipLine.go) so I have something to compare against?

Thanks,
— Scott

**Comment by suntong** [comment]
that `Next` was actually added last minute, and should not be there in the first place. For either case, the Getline loop does not advance the NR.

OK. I'll provide a simpler AWK version of SkipLine.go in a sec.

**Comment by suntong** [comment]
First, getline in awk should advance the NR, and read the next lines in sequence:

```
$ seq 6 | awk '/2/{ getline; getline; }; 1'
1
4
5
6
```

**Comment by suntong** [comment]
Skip lines from /2/ to /^5/:

```
$ seq 6 | awk '/2/{ while ($0 !~/^5/) { getline;} next; }; 1'
1
6
```

**Comment by suntong** [comment]
Hope you can find some time to fix it soon. Thanks.

**Comment by spakin** [comment]
> Confirmed that it is a bug -- according to https://godoc.org/github.com/spakin/awk#Script.GetLine

Please read the whole paragraph:

> GetLine reads the next record from an input stream and returns it. If the argument to GetLine is nil, GetLine reads from the current input stream and increments NR. Otherwise, it reads from the given io.Reader and does not increment NR. **Call SetF(0, ...) on the Value returned by GetLine to perform the equivalent of AWK's getline with no variable argument.**

That is, you need some `SetF(0, `*variable*`)` calls to mimic a no-argument `getline`.  Your `/2/{ getline; getline; }; 1` example should therefore be written as follows in Go:

```Go
scr := awk.NewScript()
scr.AppendStmt(func(s *awk.Script) bool {
        return s.F(0).Match("2")
}, func(s *awk.Script) {
        v, err := s.GetLine(nil)
        if err != nil {
                return
        }
        s.SetF(0, v)

        v, err = s.GetLine(nil)
        if err != nil {
                return
        }
        s.SetF(0, v)
})
scr.AppendStmt(nil, nil)
```

Your `/2/{ while ($0 !~/^5/) { getline;} next; }; 1` should be written as follows:

```Go
scr := awk.NewScript()
scr.AppendStmt(func(s *awk.Script) bool {
        return s.F(0).Match("2")
}, func(s *awk.Script) {
        for !s.F(0).Match("^5") {
                v, err := s.GetLine(nil)
                if err != nil {
                        return
                }
                s.SetF(0, v)
        }
        s.Next()
})
scr.AppendStmt(nil, nil)
```

And your `/^B/{ while ($0 !~/^E/) { getline;} next; }; 1` example should be written as follows:

```Go
scr := awk.NewScript()
scr.AppendStmt(func(s *awk.Script) bool {
        return s.F(0).Match("^B")
}, func(s *awk.Script) {
        for !s.F(0).Match("^E") {
                v, err := s.GetLine(nil)
                if err != nil {
                        return
                }
                s.SetF(0, v)
        }
        s.Next()
})
scr.AppendStmt(nil, nil)
```

As for https://github.com/suntong/lang/blob/master/lang/Go/src/text/awk/SkipLine.go, it seems that this is the AWK code you had in mind:

```AWK
{
    # Validate the current line.
    for (i = 1; i <= 3; i++) {
        if ($i != (NR - 1)*3 + i)
            check((NR - 1)*3 + i, $i)
    }
    print ".", NR, $0

    # Skip till ^7.
    for (getline line; line !~ /^7/; ) {
        print ">", NR, line
        next
    }
}

END {
    print "Passed."
}

function check(a, b) {
    if (a == b)
        return
    print "Received != expected" > "/dev/stderr"
    exit 1
}
```

That does expose a problem with the [`awk` package](https://github.com/spakin/awk)'s `Next` call, which fails to break out of the enclosing `for` loop.  I'll see if I can fix that.  In the meantime, adding a `return` after the `s.Next()` should make the Go version produce the same results as the AWK version.

— Scott

**Comment by suntong** [comment]
Thanks a lot for your detailed explanation!! Will do.
