### ISSUE TITLE
Invalid rune in input data (Chinese word )

### ISSUE THREAD

**Issue by huiyangchen** [spakin/awk#6]
file, err := os.Open(ip_datafile)
s.Run(file)

I try to run script with the record file in Chinese,  then it meet the err "Invalid rune in input data". the record like "1.15.120.0-1.15.127.255#中国#天津#天津#方正宽带/电信". The word "带/电信" can not be read correctly. It was changed to the  character � at return statement in your method "makeRecordSplitter()" inside the "script.go".

I am confused now,when I used the scanner.text() , the character "带/电信" is ok. Can you help me to find out problem I meet? Thanks

**Comment by spakin** [comment]
Could you please post a small but complete failing program and an associated data file?  The following program worked for me when I gave it a `file.txt` file containing three lines of "1.15.120.0-1.15.127.255#中国#天津#天津#方正宽带/电信":
```Go
package main

import (
        "fmt"
        "github.com/spakin/awk"
        "os"
)

func main() {
        lines := make([]string, 0)
        s := awk.NewScript()
        s.AppendStmt(nil, func(s *awk.Script) {
                lines = append(lines, s.F(0).String())
        })
        file, err := os.Open("file.txt")
        if err != nil {
                panic(err)
        }
        if err := s.Run(file); err != nil {
                panic(err)
        }
        fmt.Printf("Data = %#v\n", lines)
}
```

Is it possible that your data file isn't UTF-8?  That could explain the erroneous "�" glyph.

— Scott

[file.txt](https://github.com/spakin/awk/files/530762/file.txt)

**Comment by suntong** [comment]
I believe this issue can be closed now.

**Comment by spakin** [comment]
I don't know what you mean by "unless more info on how `makeRecordSplitter()` was called".  I'll close the issue for now, but feel free to open it again if you have something to add.

**Comment by suntong** [comment]
was _provided_, :(

**Comment by spakin** [comment]
Okay.  Reopen the issue if you can construct a small but complete failing program with an associated data file.  Like I wrote above, my test program and test input didn't return any "�" characters.
