### ISSUE TITLE
Need Print() or Printf()

### ISSUE THREAD

**Issue by suntong** [spakin/awk#7]
Hi Scott, 

in Awk, besinde printing with new line using `print`, it has also provided `printf` so that make it possible to print something without printing new line at the end.

So please provide either `Print()` or `Printf()`. Missingis them are more inconvenient than missing `Println()`, as we can use `Print()` to do `Println()` but not the other way round. 

Please consider, thanks.

**Comment by spakin** [comment]
Either use Go's regular `fmt.Printf` or set the output record separator to an empty string using `Script.SetORS("")`.

If there's a reason neither of those works for you, please provide more information as to why (e.g., a short AWK script that you're having trouble converting to Go).

— Scott

**Comment by suntong** [comment]
The problem is that only Go's regular `fmt.Printf` is not enough, as the output is not always to `stdout`. So people always have to use `fmt.Fprintf` with a output file handler. I know that's not a big deal, so providing Print() or Printf() will have little significant, just a convenient, that's all. 

Alright, I'm OK not having them. :-)

**Comment by spakin** [comment]
Your sample script uses AWK's `print` statement, which writes to stdout and includes the newline character (or, more precisely, `ORS`).  It therefore corresponds pretty closely to `awk`'s existing `Script.Println`:
```Go
package main

import (
	"github.com/spakin/awk"
	"os"
)

func main() {
	s := awk.NewScript()
	s.AppendStmt(awk.Auto("3:", "6:"), func(s *awk.Script) {
		s.SetF(0, s.NewValue("+ "+s.F(0).String()))
		s.Println()
		s.Next()
	})
	s.AppendStmt(nil, nil)
	s.Run(os.Stdin)
}
```

I can't think of a good example of an AWK program that uses `print` or `printf` yet doesn't map easily to either `Script.Println`, `fmt.Printf`, or `fmt.Fprintf` (perhaps using `Script.Output`).  Can you?

I'll close this issue for now, but if you find some AWK `print`/`printf` handling that's particularly awkward to reproduce with the Go package, do post it here and reopen the issue.

— Scott

**Comment by suntong** [comment]
Thanks Scott.
